import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import MenuNav from '@/components/layout/left-menu-nav';
import TopMenuNav from '../../components/layout/top-menu-nav';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="grid grid-cols-12">
          <TopMenuNav />
          {/* left side nav */}
          <div className="col-span-2 relative">
            <MenuNav />
          </div>
          <div className="col-span-10 p-4 pt-16">{children}</div>
        </main>
      </body>
    </html>
  );
}
